<?php
/**
 * Distribution script minify
 *
 * @author Leonardo Laureti
 * @license GPL-2.0-or-later
 */

(php_sapi_name() === 'cli' && isset($_SERVER['DIST'])) || print('For internal purpose only.') && exit(1);

define('BASEPATH', realpath(__DIR__ . '/../inc/dist'));

$files = [
	'bulk-actions-script.php',
	'postprocess-script.php',
	'thumbnailer-script.php'
];

foreach ($files as $filename) {
	$t0 = hrtime(true);
	$filepath = BASEPATH . '/' . $filename;

	if (! file_exists($filepath) && ! is_readable($filepath)) {
		trigger_error(sprintf('File Error "%s"', $filepath), E_USER_WARNING);
		continue;
	}

	$file = file_get_contents($filepath);

	// file heading
    preg_match('/<\?php.*?\?>/s', $file, $tags);
	// script wrapper
	preg_match('/(<script[^>]*?>)(.*?)(<\/script>)/s', $file, $wrap);

	$script = $wrap[2];
	// turn off debug
	$script = str_replace('const debug = true;', 'const debug = false;', $script);
	// strip block comments
	$script = preg_replace('/\/\*.*?\*\//s', '', $script);
	// strip inline comments
	$script = preg_replace('/ \/\/[^\n]+/s', '', $script);
	// wrap inline "else" statements
	$script = preg_replace('/(else)\s/', "$1\0", $script);
	// wrap reserved words
	$script = preg_replace('/(new|return|async|class|function|throw|const|let|var|await|using|static|case|delete) /', "\$1\0", $script);
	$script = preg_replace('/ (in|of|instanceof|typeof|extends) /', "\0\$1\0", $script);
	// replace white-space on strings
	$script = preg_replace_callback('/\B[\'"`]([^\'"`]+)[\'"`]\B/', function ($matches) {
		return str_replace(' ', "\0", $matches[0]);
	}, $script);
	// revert substitutions and inline the code
	$script = str_replace([' ', "\n", "\0"], ['', '', ' '], $script);
	// cleanup
	$script = str_replace(['; ', ';}', ";)", '}else {'], [';', '}', ')', '}else{'], $script);
	// join contiguous properties
	$matched = true;
	while ($matched) {
		$matched = preg_match('/(const|let|var) ([^;]+);(const|let|var) /', $script, $matches);
		$matched = $matched && $matches[1] === $matches[3];
		if ($matched) {
			$script = preg_replace_callback('/(const|let|var) ([^;]+);(const|let|var) /', function ($matches) {
				return $matches[1] === $matches[3] ? "{$matches[1]} {$matches[2]}," : $matches[0];
			}, $script);
		}
	}
	// remove right ending semicolon
	$script = rtrim($script, ';');

	$tags = str_replace('?>', "/*! This file is generated by src/distribution.php */\n\n?>", $tags[0]);

	$data = "{$tags}{$wrap[1]}{$script}{$wrap[3]}\n";
	$out = BASEPATH . '/' . str_replace('-script', '-script-min', $filename);

	if (! is_writable(dirname($out))) {
		trigger_error(sprintf('File Permission Error "%s"', $out), E_USER_WARNING);
		continue;
	}

	$outbytes = file_put_contents($out, $data);

	$t1 = hrtime(true);
	$inbytes = filesize($filepath);
	$inoutsaving = $inbytes % $outbytes / 100;

	printf("%s=>%s minified %4\$dB (%5\$d%% %3\$dB) %6\$du\n", basename($filepath), basename($out), $inbytes, $outbytes, $inoutsaving, $t1 - $t0);
}

